CREATE TABLE IF NOT EXISTS mpaa_ratings (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(200),
    release_date     DATE NOT NULL,
    duration         INTEGER NOT NULL,
    mpaa_rating_id   INTEGER REFERENCES mpaa_ratings (id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id  INTEGER NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS user_friends (
    user_id   INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status    VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id INTEGER NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(100) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id     INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    film_id     INTEGER NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    useful      INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id   INTEGER NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    user_id     INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    is_positive BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_films_mpaa_rating_id ON films (mpaa_rating_id);
CREATE INDEX IF NOT EXISTS idx_film_genre_film_id ON film_genre (film_id);
CREATE INDEX IF NOT EXISTS idx_film_genre_genre_id ON film_genre (genre_id);
CREATE INDEX IF NOT EXISTS idx_user_friends_user_id ON user_friends (user_id);
CREATE INDEX IF NOT EXISTS idx_user_friends_friend_id ON user_friends (friend_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_film_id ON film_likes (film_id);
CREATE INDEX IF NOT EXISTS idx_film_likes_user_id ON film_likes (user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_film_id ON reviews (film_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews (user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_useful ON reviews (useful DESC);
CREATE INDEX IF NOT EXISTS idx_review_likes_review_id ON review_likes (review_id);
CREATE INDEX IF NOT EXISTS idx_review_likes_user_id ON review_likes (user_id);
